#!/bin/bash

# Create a simple Teams app package instructions
echo "📱 TEAMS APP PACKAGE CREATION GUIDE"
echo "================================="
echo ""
echo "✅ Step 1: Icons Required"
echo "You need to create two PNG icons:"
echo "  - color.png: 192x192 pixels (full color app icon)"
echo "  - outline.png: 32x32 pixels (monochrome outline icon)"
echo ""
echo "🎨 Quick Icon Creation Options:"
echo "1. Use online tools like:"
echo "   - Canva.com"
echo "   - figma.com"
echo "   - Any online PNG generator"
echo ""
echo "2. Use your existing app logo/icon"
echo ""
echo "3. Simple text icons with your app colors (#007AFF background)"
echo ""
echo "📦 Step 2: Create ZIP Package"
echo "Once you have the icons:"
echo "1. Put color.png, outline.png, and manifest.json in this folder"
echo "2. Select all three files"
echo "3. Right-click → 'Compress 3 items'"
echo "4. Rename the ZIP to 'ai-avatar-teams-app.zip'"
echo ""
echo "🚀 Step 3: Upload to Teams"
echo "1. Open Microsoft Teams"
echo "2. Click 'Apps' in the left sidebar"
echo "3. Click 'Manage your apps' (bottom left)"
echo "4. Click 'Upload an app'"
echo "5. Select your ZIP file"
echo ""
echo "✨ Your app will now be available in Teams!"
echo ""
echo "📁 Files in this directory:"
ls -la
